import { jsPDF } from 'jspdf';
import type { RentInvoice, Tenant, Property } from '../types';
import { formatCurrency } from './helpers';

export const generateRentReceiptPDF = (invoice: RentInvoice, tenant: Tenant, property: Property) => {
  const doc = new jsPDF();
  
  // Header background
  doc.setFillColor(2, 132, 199); // Brand primary blue
  doc.rect(0, 0, 210, 38, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('STAYHUB RENT RECEIPT', 14, 22);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Receipt #: ${invoice.invoiceNumber}`, 140, 18);
  doc.text(`Date: ${invoice.paidDate || new Date().toISOString().split('T')[0]}`, 140, 26);

  // Property Details
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(property.name, 14, 52);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`${property.address}, ${property.city}, ${property.state} - ${property.pincode}`, 14, 58);
  doc.text(`Helpline: ${property.helplineNumber}`, 14, 64);

  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 72, 196, 72);

  // Tenant Info Box
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 78, 182, 36, 3, 3, 'F');

  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.text('TENANT DETAILS', 20, 88);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Tenant Name: ${tenant.fullName}`, 20, 96);
  doc.text(`Room & Bed: Room ${tenant.roomNumber} (${tenant.bedNumber})`, 20, 104);
  doc.text(`Mobile: ${tenant.phone}`, 110, 96);
  doc.text(`Billing Period: ${invoice.billingPeriod}`, 110, 104);

  // Table Header
  doc.setFillColor(241, 245, 249);
  doc.rect(14, 122, 182, 10, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  doc.text('DESCRIPTION', 20, 128);
  doc.text('AMOUNT (INR)', 150, 128);

  // Line items
  let y = 138;
  const items = [
    { name: 'Monthly Rent Fee', amount: invoice.rentAmount },
    { name: 'Electricity Charges', amount: invoice.electricityCharge },
    { name: 'Mess Charges', amount: invoice.messCharge },
    { name: 'Late Fee', amount: invoice.lateFee },
    { name: 'Discount / Waiver', amount: -invoice.discount },
  ];

  items.forEach(item => {
    if (item.amount !== 0) {
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      doc.text(item.name, 20, y);
      doc.text(formatCurrency(item.amount), 150, y);
      y += 8;
    }
  });

  // Total line
  doc.line(14, y + 2, 196, y + 2);
  y += 10;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('TOTAL AMOUNT PAID:', 20, y);
  doc.text(formatCurrency(invoice.totalPayable), 150, y);

  // Payment Status Stamp
  doc.setDrawColor(16, 185, 129);
  doc.setFillColor(236, 253, 245);
  doc.roundedRect(14, y + 14, 182, 24, 3, 3, 'FD');

  doc.setTextColor(4, 120, 87);
  doc.setFontSize(12);
  doc.text('✔ PAYMENT VERIFIED & CONFIRMED', 20, y + 26);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Payment Mode: ${invoice.paymentMethod || 'UPI'}  |  Transaction ID: ${invoice.transactionId || 'TXN-998811'}`, 20, y + 33);

  // Footer Sign off
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(8);
  doc.text('This is a computer-generated digital receipt generated by StayHub PG Management OS.', 14, 280);

  doc.save(`StayHub_Receipt_${invoice.invoiceNumber}.pdf`);
};

export const generateRentalAgreementPDF = (tenant: Tenant, property: Property) => {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('DIGITAL RESIDENTIAL RENTAL AGREEMENT', 14, 22);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Execution Date: ${tenant.joiningDate}`, 14, 28);
  doc.line(14, 32, 196, 32);

  doc.setTextColor(30, 41, 59);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('1. PARTIES TO THE AGREEMENT:', 14, 42);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`LESSOR / PROPERTY OWNER: ${property.name} (${property.address}, ${property.city})`, 20, 50);
  doc.text(`LESSEE / RESIDENT: ${tenant.fullName} (Aadhaar: ${tenant.aadhaarNumber})`, 20, 58);
  doc.text(`Permanent Address: ${tenant.permanentAddress}`, 20, 66);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('2. ACCOMMODATION ALLOCATION:', 14, 78);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Allocated Room: Room ${tenant.roomNumber} (${tenant.bedNumber})`, 20, 86);
  doc.text(`Monthly Rent: ${formatCurrency(tenant.rentAmount)} (payable by 5th of each month)`, 20, 94);
  doc.text(`Security Deposit: ${formatCurrency(tenant.securityDeposit)} (refundable upon checkout)`, 20, 102);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('3. RULES AND REGULATIONS:', 14, 114);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const rules = [
    '• Rent must be remitted by the 5th day of every calendar month. Late fee of Rs. 100/day applies thereafter.',
    '• Resident shall maintain peaceful environment. Loud music/disturbances post 10:00 PM are strictly prohibited.',
    '• Non-residents / Visitors are allowed only in visitor lounge up to 8:00 PM with gate entry pass approval.',
    '• Consumption of illegal substances, smoking, or alcohol inside PG premises is grounds for immediate eviction.',
    '• Minimum notice period for checkout is 30 days. Deposit refund requires clearance of damage inspection.'
  ];
  let ry = 122;
  rules.forEach(r => {
    doc.text(r, 20, ry);
    ry += 8;
  });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('4. DIGITAL SIGNATURE & ACCEPTANCE:', 14, ry + 10);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Digitally Accepted by Resident: ${tenant.fullName}`, 20, ry + 20);
  doc.text(`Date & Time: ${tenant.agreementAcceptedDate || tenant.joiningDate}`, 20, ry + 28);
  doc.text(`Verification Code: DIGI-SIG-${tenant.id.toUpperCase()}-VERIFIED`, 20, ry + 36);

  doc.save(`StayHub_Rental_Agreement_${tenant.fullName.replace(/\s+/g, '_')}.pdf`);
};
